services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    command: start-dev
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && grep 'overall status.*UP' <&3"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - keycloak-data:/opt/keycloak/data

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moustass_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  auth:
    build: ./auth
    ports:
      - "3000:3000"
    env_file:
      - auth/.env
    depends_on:
      mysql:
        condition: service_healthy

  user:
    build: ./user
    ports:
      - "4000:4000"
    env_file:
      - user/.env
    depends_on:
      mysql:
        condition: service_healthy
      vault:
        condition: service_started

  front:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./front:/app
    command: npx http-server -p 8081
    ports:
      - "8081:8081"
    depends_on:
      - auth

  vault:
    image: hashicorp/vault:1.14.1
    ports:
      - "8201:8200"      # port host diffÃ©rent
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    volumes:
      - vault-data:/vault/file
    command: server -dev -dev-root-token-id=root



volumes:
  mysql-data:
  keycloak-data:
  vault-data: